table Customer_Details
	lineageTag: 221b2df8-ff37-47fe-a3cf-bb5bc80321e3

	column 'Customer ID'
		dataType: string
		lineageTag: 3a0c4af1-a3d2-41aa-be7d-a09d6e4757f3
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: c92487e9-083e-4836-8420-86a0c73b1673
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column 'Loan ID'
		dataType: string
		lineageTag: 4a6ca6c5-0aae-4196-9809-37691fc7e46f
		summarizeBy: none
		sourceColumn: Loan ID

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: 264d0f62-fc2f-4451-a74c-d882679c2465
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 2af66de2-e725-4a1d-b48d-0ccd05c8ab68
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column 'Country '
		dataType: string
		lineageTag: c0c0e73c-90f6-4472-b0ee-48a69fad8b64
		dataCategory: Country
		summarizeBy: none
		sourceColumn: "Country "

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 12e83346-981c-48c0-a54b-5e33cf10b9d0
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Job Classification'
		dataType: string
		lineageTag: 55111ecd-c0c4-41f4-a0db-dba613c4e642
		summarizeBy: none
		sourceColumn: Job Classification

		annotation SummarizationSetBy = Automatic

	column 'Marital Status '
		dataType: string
		lineageTag: 74612aa9-365e-4d01-a98c-6c211e038088
		summarizeBy: none
		sourceColumn: "Marital Status "

		annotation SummarizationSetBy = Automatic

	column 'Account Type '
		dataType: string
		lineageTag: 32f92159-e241-4147-a108-3e4a4c4369e8
		summarizeBy: none
		sourceColumn: "Account Type "

		annotation SummarizationSetBy = Automatic

	column 'Annual Income'
		dataType: int64
		formatString: 0
		lineageTag: b61da100-1ca6-443f-b31c-5df2b783d1db
		summarizeBy: sum
		sourceColumn: Annual Income

		annotation SummarizationSetBy = Automatic

	column 'Years in current job'
		dataType: string
		lineageTag: 45a8c47f-c4b9-48ce-8a27-de7a5098d954
		summarizeBy: none
		sourceColumn: Years in current job

		annotation SummarizationSetBy = Automatic

	partition Customer_Details = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\shraban\OneDrive\Music\Power BI\DAX_Capstone Proj 2\Dataset\Customer.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer ID", type text}, {"Customer Name", type text}, {"Loan ID", type text}, {"Gender", type text}, {"Age", Int64.Type}, {"Country ", type text}, {"State", type text}, {"Job Classification", type text}, {"Marital Status ", type text}, {"Account Type ", type text}, {"Annual Income", Int64.Type}, {"Years in current job", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

