table Customers_Dim_Old
	lineageTag: f48a95bb-62d3-4d04-9638-3271db9fca59

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 235c0020-b013-4f55-8488-ead758c91c58
		summarizeBy: count
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column Prefix
		dataType: string
		lineageTag: 29ce1911-ec2e-476b-9a56-02a577223069
		summarizeBy: none
		sourceColumn: Prefix

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: 2fbfdaa9-9c4d-4405-a149-2806001a12a3
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 53d848be-5159-47ad-9e38-e6ec200f6ccc
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column BirthDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: fb887277-2310-4960-b9fb-2d1f0b5f5fde
		summarizeBy: none
		sourceColumn: BirthDate

		variation Variation
			isDefault
			relationship: bd055edd-c4f4-495a-9838-257831c8d99a
			defaultHierarchy: LocalDateTable_1c9ebd8a-b6b3-40b1-8b53-ef786da9d178.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MaritalStatus
		dataType: string
		lineageTag: 5dbbfdec-918c-4e1f-9c63-09ebb9ebe5cf
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: b2e72508-ed4a-45fa-b7dd-29c9759e2b14
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column EmailAddress
		dataType: string
		lineageTag: 0ee4a940-bd3f-423c-987f-a07fda4ecd24
		summarizeBy: none
		sourceColumn: EmailAddress

		annotation SummarizationSetBy = Automatic

	column AnnualIncome
		dataType: int64
		formatString: 0
		lineageTag: 2428b4be-4ae5-42d6-87a6-89854ce01f0b
		summarizeBy: sum
		sourceColumn: AnnualIncome

		annotation SummarizationSetBy = Automatic

	column TotalChildren
		dataType: int64
		formatString: 0
		lineageTag: 90f40800-96e4-40b3-aede-c12dd3285a3c
		summarizeBy: sum
		sourceColumn: TotalChildren

		annotation SummarizationSetBy = Automatic

	column EducationLevel
		dataType: string
		lineageTag: ed9a3a84-a90f-4bc5-9966-83abbe2d1bb1
		summarizeBy: none
		sourceColumn: EducationLevel

		annotation SummarizationSetBy = Automatic

	column Occupation
		dataType: string
		lineageTag: fdb86644-3172-4f6f-83e9-7eb8b89e532d
		summarizeBy: none
		sourceColumn: Occupation

		annotation SummarizationSetBy = Automatic

	column HomeOwner
		dataType: string
		lineageTag: 19e6cda6-a027-4a7f-a902-4981f2f45f17
		summarizeBy: none
		sourceColumn: HomeOwner

		annotation SummarizationSetBy = Automatic

	column Age = DATEDIFF(Customers_Dim_Old[BirthDate].[Date],Today(),YEAR)
		formatString: 0
		lineageTag: b8aa4a70-fc1d-4c0e-8aa9-7f84765d2b8f
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Age Group' =
			
			SWITCH(
			    TRUE(),
			    Customers_Dim_Old[Age]<=50,"41-50",
			    Customers_Dim_Old[Age]<=60,"51-60",
			    Customers_Dim_Old[Age]<=70,"61-70",
			    Customers_Dim_Old[Age]<=80,"71-80",
			    Customers_Dim_Old[Age]<=90,"81-90",
			    Customers_Dim_Old[Age]>90,"91-120")
		lineageTag: 376560e1-8f59-4eec-98f1-657298ddd7c2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Customers_Dim_Old = m
		mode: import
		queryGroup: Dim_Table
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\shraban\OneDrive\Music\Power BI\DAX_Capstone Proj 1\Dataset\Customers_Table.csv"),[Delimiter=",", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerKey", Int64.Type}, {"Prefix", type text}, {"FirstName", type text}, {"LastName", type text}, {"BirthDate", type date}, {"MaritalStatus", type text}, {"Gender", type text}, {"EmailAddress", type text}, {"AnnualIncome", Int64.Type}, {"TotalChildren", Int64.Type}, {"EducationLevel", type text}, {"Occupation", type text}, {"HomeOwner", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

