table Products_Dim
	lineageTag: a6c5596a-4ade-4dc9-97bd-2202e456cd64

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 7b7446be-dd3f-40b7-ac9b-939b44540a40
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column ProductSubcategoryKey
		dataType: int64
		formatString: 0
		lineageTag: f68918e6-0217-4fa6-a307-4dbfe5d3a45b
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		annotation SummarizationSetBy = Automatic

	column ProductSKU
		dataType: string
		lineageTag: d10e7dc1-f16c-40f4-aca7-7b66373eae69
		summarizeBy: none
		sourceColumn: ProductSKU

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: a150803f-e02b-42b6-9ff9-029f501bcc5c
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column ModelName
		dataType: string
		lineageTag: 3f77cad4-388f-4378-9318-c04f188be8d9
		summarizeBy: none
		sourceColumn: ModelName

		annotation SummarizationSetBy = Automatic

	column ProductDescription
		dataType: string
		lineageTag: 8a5f2957-fb59-45da-a496-80a62cf79ecc
		summarizeBy: none
		sourceColumn: ProductDescription

		annotation SummarizationSetBy = Automatic

	column ProductColor
		dataType: string
		lineageTag: ce6638c1-2fbe-4289-bc86-7d004d230771
		summarizeBy: none
		sourceColumn: ProductColor

		annotation SummarizationSetBy = Automatic

	column ProductSize
		dataType: string
		lineageTag: 86dec83b-1789-4a77-bd33-86c783b84fda
		summarizeBy: none
		sourceColumn: ProductSize

		annotation SummarizationSetBy = Automatic

	column ProductStyle
		dataType: string
		lineageTag: dcc75f84-c000-4086-82de-1f949dfc1ff7
		summarizeBy: none
		sourceColumn: ProductStyle

		annotation SummarizationSetBy = Automatic

	column ProductCost
		dataType: double
		lineageTag: 94dfd645-8c84-4ac4-b010-6fb90647f185
		summarizeBy: sum
		sourceColumn: ProductCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductPrice
		dataType: double
		lineageTag: 3e83046b-4f9e-4ee8-a442-89ccd7f8efc5
		summarizeBy: sum
		sourceColumn: ProductPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Products_Dim = m
		mode: import
		queryGroup: Dim_Table
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\shraban\OneDrive\Music\Power BI\DAX_Capstone Proj 1\Dataset\Products_Table.csv"),[Delimiter=",", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductKey", Int64.Type}, {"ProductSubcategoryKey", Int64.Type}, {"ProductSKU", type text}, {"ProductName", type text}, {"ModelName", type text}, {"ProductDescription", type text}, {"ProductColor", type text}, {"ProductSize", type text}, {"ProductStyle", type text}, {"ProductCost", type number}, {"ProductPrice", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

